### ISSUE TITLE
Support for multiple flaps

### ISSUE THREAD

**Issue by durosity** [wylanswets/homebridge-sure-petcare-platform#11]
I'm curious as to if this would work with two cat flaps?  I only have one at present but planning to add a second one at the same home.

**Comment by wylanswets** [comment]
Hey @durosity. Yes, the plugin is designed to handle any and all accessories that the service handles. If you have 300 doors (you'd be rich) it should work fine (but might be slow).

**Comment by durosity** [comment]
Well I have one ordered coming tomorrow so hopefully will work!  Thanks!
