### ISSUE TITLE
Is it possible to add curfew mode...

### ISSUE THREAD

**Issue by momonunu** [wylanswets/homebridge-sure-petcare-platform#12]
...or just dont set any lockmode?

Thx

**Comment by wylanswets** [comment]
Hey @momonunu,

I'm not sure I'm understanding exactly what you're asking, but it appears curfew mode is just a way to set the lock to a state at a certain time of day... and that's something that homekit is pretty good at by itself in the "automations" section.

Let me know if there's something more specific you need or if I can close out this issue.

Thanks!

**Comment by momonunu** [comment]
Thx for the reply no its ok.
