### ISSUE TITLE
2nd PetDoor

### ISSUE THREAD

**Issue by Sommi486** [wylanswets/homebridge-sure-petcare-platform#17]
I‘ve installed and added a second PetDoor in my house. 

Only the first one is shown and Trigger the Pets didn‘t work anymore. 

All sensors are shown as activated.

**Comment by wylanswets** [comment]
Hey @Sommi486 is this still an issue for you?

By chance have you tried resetting the plugin?

**Comment by Sommi486** [comment]
Hey @wylanswets thanks for your answer and glad to see that the plugin will be further developed! 

After restarting HomeBridge the second PetDoor was shown and reacted as the first.

**Comment by wylanswets** [comment]
Veeeeeeeeeeery interesting lol. I was thinking to myself there wasn't a reason multiple wouldn't show up haha. Glad it is working out!
