### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ecrode** [wylanswets/homebridge-sure-petcare-platform#8]
Right now only locking mode supported by the plugin is "keep pets in", whereas I am primarily interested in "keep pets out" / "lock both ways" for times I see my cat bringing a trophy from her hunt home (mostly lizards).

I understand that homekit treats the switch as binary, thus it's natural to simply pass "1" to setLock function underlying api treats as keep pets indoors condition, but can a settings be added to customize the value between default (1) and keep out (2) or bidirectional (3).

Perhaps something like this:

> SurePetcarePetFlap.prototype._setLockState = function(targetState, callback, context) {
    if (context == "internal") return callback(null); // we set this state ourself, no need to react to it
    var self = this;
    var state = (targetState && this.config.lock_state) ? this.config.lock_state ? targetState;
    this.session.setLock(this.lock.id, state , function(data) {
        self.service
          .getCharacteristic(Characteristic.LockCurrentState)
          .setValue(targetState, null, "internal");
        callback(null);
    });
}

Thanks

**Comment by wylanswets** [comment]
Hi @ecrode! I have added support for this in the latest version, 0.1.3. Please see the change log in the readme (homepage of the project) after updating on how to adjust it to your liking!
